# Jekyll
exclude: ['nbproject', 'README.md', 'manifest.yml', 'rakefile.rb','s3_website.yml']
permalink:   /:title
url:         http://aliecett.wicp.net/
safe:        false

future:      false
pygments:    true
markdown:    rdiscount

# Only First P Plugin
only_first_p:
    show_read_more_link: true
    read_more_link_text: 'Read more'