# Jekyll
exclude: ['nbproject', 'README.md', 'manifest.yml', 'rakefile.rb','s3_website.yml']
permalink:   /:title
url:         http://aliecett.wicp.net/
production_url : http://Aliece.github.io
safe:        false

future:      false
pygments:    true
markdown:    rdiscount

# Site
aliece:
    title: aliece

# Only First P Plugin
only_first_p:
    show_read_more_link: false
